name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format check
        run: terraform -chdir=terraform fmt -check

      - name: Terraform init
        run: terraform -chdir=terraform init -backend=false

      - name: Terraform validate
        run: terraform -chdir=terraform validate

      - name: Validate required files
        run: |
          test -f app/app.py
          test -f app/requirements.txt
          test -f app/Dockerfile

      - name: Set image tag
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/standardized-cicd-app:${IMAGE_TAG} ./app
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/standardized-cicd-app:${IMAGE_TAG} ${{ secrets.DOCKERHUB_USERNAME }}/standardized-cicd-app:latest

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/standardized-cicd-app:${IMAGE_TAG}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/standardized-cicd-app:latest